# 1. Neural Network Basics 

### (a)  Sigmoid function and its derivative 
$$\sigma(x) = \frac{1}{1-e^{-x}}= \frac{e^x}{e^x-1} \space,\space\space\space
  \frac{\partial \sigma(x)}{\partial x} = \frac{-e^x }{(e^x-1)^2} = \sigma(x) (1-\sigma(x))$$

### (b) Softmax function and its derivative
$$\space \hat y_i = softmax(x_i) =  \frac{e^{x_i}}{\sum_j e^{x_j}} $$

$$\frac{\partial \hat y_i}{\partial  x_j} =  \frac{e^{x_i}{\sum_j e^{x_j}} - e^{x_i}e^{x_i}}{(\sum_j e^{x_j})^2} = \frac{e^{x_i} ( {\sum_j e^{x_j}} - e^{x_i})}{(\sum_j e^{x_j})^2} =
\frac{e^{x_i}  }{\sum_j e^{x_j} } \frac{ {\sum_j e^{x_j}} - e^{x_i}  }{\sum_j e^{x_j} } =
\hat y_i (1 - \hat y_i),  \space\space\space for  \space\space\space i = j $$

$$\frac{\partial \hat y_i}{\partial  x_j} =  \frac{ 0 - e^{x_i}e^{x_j} }{(\sum_j e^{x_j})^2}  =
\frac{e^{x_i}  }{\sum_j e^{x_j} } \frac{ - e^{x_j}  }{\sum_j e^{x_j} } =
- \hat y_i  \hat y_j, \space\space\space for  \space\space\space i \neq j $$

$$\frac{\partial \hat y_i}{\partial  x_j} = \{^{\hat y_j (1 -\hat y_j),\space\space\space for \space\space\space i = j }_{- \hat y_i  \hat y_j, \space\space\space for  \space\space\space i \neq j} =
\hat y_j (\delta_{ij} - \hat y_i)  $$



### (c) Cross Entropy Loss and its derivative 
$$ J = CE(y, \hat{y}) = - \sum_i y_i \space \log (\hat y_i),\space\space\space \hat y_i = softmax(x_i) =  \frac{e^{x_i}}{\sum_j e^{x_j}}$$

$$\frac{\partial J}{\partial x_i} = \frac{\partial J}{\partial \hat y_i} \frac{\partial \hat y_i}{\partial x_i} = \frac{\partial J}{\partial \hat y_i} \hat y_i (\delta_{ij} - \hat y_j)$$

$$ \frac{\partial J}{\partial \hat y_i} = - \sum_j \frac{y_j}{\hat y_i} = -  \frac{1}{\hat y_i} \sum_j  y_j   $$

$$\frac{\partial J}{\partial x_i} = (\hat y_j - \delta_{ij}) \sum_j  y_j = \hat y_j \sum_j  y_j - \delta_{ij} \sum_j  y_j = \hat y_j \sum_j  y_j - y_i $$ 
for one hot encoded vecter y, $\sum_j  y_j = 1, \space\space\space   \delta_{ij} \sum_j  y_j  = y_i$,

$$ { \frac{\partial J}{\partial x} =  \hat y - y} $$

### (d) Derivative of Forward Propagation Gradient 

 $$ h= sigmoid(xW_1 + b_1) = \sigma (xW_1 + b_1), \space\space\space\space\space\space 
   \hat y = softmax (hW_2 + b2) $$
   
 $ J = CE (y, \hat y) $,
 find $\frac {\partial J}{\partial x} $
 
 $$ \frac{\partial J}{\partial x} = \frac{\partial J }{\partial h} \frac {\partial h}{\partial x} $$
 
 $$  \frac {\partial h}{\partial  x} = W_1^T \sigma (1- \sigma)   $$
 
 $$  \frac{\partial J}{\partial h} = W_2^T (\hat y   -   y)  $$
 
 $$ \frac {\partial J}{\partial x} =  W_1^T W_2^T \sigma (1- \sigma)(\hat y - y) $$
 
Similarly, we have 
$$  \frac{\partial J}{\partial b_2} = \hat y   -   y  $$
   $$  \frac{\partial J}{\partial W_2} = h(\hat y   -   y)  $$
   
$$ \frac{\partial J}{\partial b_1} = \frac{\partial J }{\partial h} \frac {\partial h}{\partial b_1} 
   =  W_2^T \sigma (1- \sigma)(\hat y - y)  $$
   
$$ \frac{\partial J}{\partial W_1} = \frac{\partial J }{\partial h} \frac {\partial h}{\partial W_1} 
   =   x W_2^T \sigma (1- \sigma)(\hat y - y)  $$

# Coding

In [1]:
import numpy as np
def softmax(x):
    """Compute the softmax function for each row of the input x.
    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. You might find numpy
    functions np.exp, np.sum, np.reshape, np.max, and numpy
    broadcasting useful for this task.
    Numpy broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
    You should also make sure that your code works for a single
    N-dimensional vector (treat the vector as a single row) and
    for M x N matrices. This may be useful for testing later. Also,
    make sure that the dimensions of the output match the input.
    You must implement the optimization in problem 1(a) of the
    written assignment!
    Arguments:
    x -- A N dimensional vector or M x N dimensional numpy matrix.
    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape
    

    if len(x.shape) > 1:
        # Matrix
        ### YOUR CODE HERE       
        x = x.astype(float)
        
#         for i,y in enumerate(x):
#             y = np.exp(y - np.max(y))
#             y = y/np.sum(y)
#             x[i] = y
        
        ### END YOUR CODE
        
        ### YOUR CODE HERE
        exp = lambda x: np.exp(x - np.max(x))
        x = np.apply_along_axis(exp, 1, x)
        
        denom = lambda x: 1.0 / np.sum(x)
        denominator = np.apply_along_axis(denom, 1, x)

        if len(denominator.shape) == 1:
            denominator = denominator.reshape((denominator.shape[0], 1))

        x = x * denominator
        ### END YOUR CODE
    else:
        # Vector
        ### YOUR CODE HERE
        
#        x = x.astype(float)
        x = x - np.max(x)
        x = np.exp(x)/np.sum(np.exp(x))
        
        ### END YOUR CODE

    assert x.shape == orig_shape
    return x

In [2]:
def test_softmax_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print ("Running basic tests...")
    test1 = softmax(np.array([1, 2]))
    print (test1)
    ans1 = np.array([0.26894142, 0.73105858])
    assert np.allclose(test1, ans1, rtol=1e-05, atol=1e-06)

    test2 = softmax(np.array([[1001, 1002], [3, 4]]))
    print (test2)
    ans2 = np.array([
        [0.26894142, 0.73105858],
        [0.26894142, 0.73105858]])
    assert np.allclose(test2, ans2, rtol=1e-05, atol=1e-06)

    test3 = softmax(np.array([[-1001, -1002]]))
    print (test3)
    ans3 = np.array([0.73105858, 0.26894142])
    assert np.allclose(test3, ans3, rtol=1e-05, atol=1e-06)

#    print ("You should be able to verify these results by hand!\n")

if __name__ == "__main__":
    test_softmax_basic()

Running basic tests...
[0.26894142 0.73105858]
[[0.26894142 0.73105858]
 [0.26894142 0.73105858]]
[[0.73105858 0.26894142]]


In [3]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.
    Arguments:
    x -- A scalar or numpy array.
    Return:
    s -- sigmoid(x)
    """

    ### YOUR CODE HERE
    s = 1.0 / (1 + np.exp(-x))
    ### END YOUR CODE

    return s


def sigmoid_grad(s):
    """
    Compute the gradient for the sigmoid function here. Note that
    for this implementation, the input s should be the sigmoid
    function value of your original input x.
    Arguments:
    s -- A scalar or numpy array.
    Return:
    ds -- Your computed gradient.
    """

    ### YOUR CODE HERE
    ds = s * (1 - s)
    ### END YOUR CODE

    return ds


def test_sigmoid_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print ("Running basic tests...")
    x = np.array([[1, 2], [-1, -2]])
    f = sigmoid(x)
    g = sigmoid_grad(f)
    print (f)
    f_ans = np.array([
        [0.73105858, 0.88079708],
        [0.26894142, 0.11920292]])
    assert np.allclose(f, f_ans, rtol=1e-05, atol=1e-06)
    print (g)
    g_ans = np.array([
        [0.19661193, 0.10499359],
        [0.19661193, 0.10499359]])
    assert np.allclose(g, g_ans, rtol=1e-05, atol=1e-06)
    print ("You should verify these results by hand!\n")

if __name__ == "__main__":
    test_sigmoid_basic();


Running basic tests...
[[0.73105858 0.88079708]
 [0.26894142 0.11920292]]
[[0.19661193 0.10499359]
 [0.19661193 0.10499359]]
You should verify these results by hand!



In [4]:
def cross_entropy(X,y):
    """
    X is the output from fully connected layer (num_examples x num_classes)
    y is labels (num_examples x 1)
    	Note that y is not one-hot encoded vector. 
    	It can be computed as y.argmax(axis=1) from one-hot encoded vectors of labels if required.
    """
    m = y.shape[0]
    p = softmax(X)
    # We use multidimensional array indexing to extract 
    # softmax probability of the correct label for each sample.
    # Refer to https://docs.scipy.org/doc/numpy/user/basics.indexing.html#indexing-multi-dimensional-arrays for understanding multidimensional array indexing.
    log_likelihood = -np.log(p[range(m),y])
    loss = np.sum(log_likelihood) / m
    return loss

梯度gradient即我们前面所求的偏导数/斜率，由于偏导数要用于梯度下降算法，所以通常在机器学习中，偏导数也称为梯度。在梯度下降算法中，我们求得的梯度最终将用于更新算法的参数。如果我们算出来的梯度有误，将很可能导致算法无法获得想要的结果，会给排查问题带来困难。所以在求得梯度之后进行梯度检查，可以检测梯度计算错误，将排查问题的精力集中在模型上而不是计算上。
梯度检查通常采用一种近似算法，

- Forward difference approximations
     $$ f^{'}(x) \approx \frac{f(x+h)-f(x)}{h} $$
- Central difference approximations
     $$ f^{'}(x) \approx \frac{f(x+h)-f(x-h)}{2h} $$
- Backward difference approximations
     $$ f^{'}(x) \approx \frac{f(x)-f(x-h)}{h} $$


In [5]:
#!/usr/bin/env python
import numpy as np
import random

# First implement a gradient checker by filling in the following functions
def gradcheck_naive(f, x):
    """ Gradient check for a function f.
    Arguments:
    f -- a function that takes a single argument and outputs the
         cost and its gradients
    x -- the point (numpy array) to check the gradient at
    """

    rndstate = random.getstate()
    random.setstate(rndstate)
    fx, grad = f(x) # Evaluate function value at original point
    h = 1e-4        # Do not change this!

    # Iterate over all indexes in x
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        ix = it.multi_index

        # Try modifying x[ix] with h defined above to compute
        # numerical gradients. Make sure you call random.setstate(rndstate)
        # before calling f(x) each time. This will make it possible
        # to test cost functions with built in randomness later.

        ### YOUR CODE HERE:
#         x[ix] += h
#         random.setstate(rndstate)
#         new_f1 = f(x)[0]
#         x[ix] -= 2*h
#         random.setstate(rndstate)
#         new_f2 = f(x)[0]
#         x[ix] += h
#         numgrad = (new_f1 - new_f2) / (2 * h)
        ### END YOUR CODE
    
        ### My CODE HERE:      
        new_f1 = f(x[ix]+h)[0]    #[0] because of  fx, grad = f(x)
        new_f2 = f(x[ix]-h)[0] 
    
        numgrad = (new_f1 - new_f2) / (2 * h)
        ### END My CODE
        
        # Compare gradients
        reldiff = abs(numgrad - grad[ix]) / max(1, abs(numgrad), abs(grad[ix]))
        if reldiff > 1e-5:
            print ("Gradient check failed.")
            print ("First gradient error found at index %s" % str(ix))
            print ("Your gradient: %f \t Numerical gradient: %f" % (grad[ix], numgrad))
            return

        it.iternext() # Step to next dimension

    print ("Gradient check passed!")


def sanity_check():
    """
    
    Some basic sanity checks.
    """
    quad = lambda x: (np.sum(x ** 2), x * 2)

    print ("Running sanity checks...")
    gradcheck_naive(quad, np.array(123.456))      # scalar test
    gradcheck_naive(quad, np.random.randn(3,))    # 1-D test
    gradcheck_naive(quad, np.random.randn(4,5))   # 2-D test
    print ("")


def your_sanity_checks():
    """
    Use this space add any additional sanity checks by running:
        python q2_gradcheck.py
    This function will not be called by the autograder, nor will
    your additional tests be graded.
    """
    print ("Running your sanity checks...")
    ### YOUR CODE HERE
    # raise NotImplementedError
    ### END YOUR CODE


if __name__ == "__main__":
    sanity_check()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



In [45]:
#!/usr/bin/env python

import numpy as np
import random

#from q1_softmax import softmax
#from q2_sigmoid import sigmoid, sigmoid_grad
#from q2_gradcheck import gradcheck_naive


def forward_backward_prop(data, labels, params, dimensions):
    """
    Forward and backward propagation for a two-layer sigmoidal network

    Compute the forward propagation and for the cross entropy cost,
    and backward propagation for the gradients for all parameters.

    Arguments:
    data -- M x Dx matrix, where each row is a training example.
    labels -- M x Dy matrix, where each row is a one-hot vector.
    params -- Model parameters, these are unpacked for you.
    dimensions -- A tuple of input dimension, number of hidden units
                  and output dimension
    """

    ### Unpack network parameters (do not modify)
    ofs = 0
    Dx, H, Dy = (dimensions[0], dimensions[1], dimensions[2])

# params con't be used directly, not sure the reason
    b = np.random.randn((Dx+1)*H + (H+1)*Dy )
    b = params + b - b
# params con't be used directly, not sure the reason

    W1 = np.reshape(b[ofs:ofs + Dx * H] , (Dx, H))
    ofs += Dx * H
    b1 = np.reshape(b[ofs:ofs + H], (1, H))
    ofs += H
    W2 = np.reshape(b[ofs:ofs + H*Dy], (H, Dy))
    ofs += H * Dy
    b2 = np.reshape(b[ofs:ofs + Dy], (1, Dy))

    ### YOUR CODE HERE: forward propagation
    h = sigmoid(np.dot(data,W1) + b1)
    yhat = softmax(np.dot(h,W2) + b2)
    ### END YOUR CODE

    ### YOUR CODE HERE: backward propagation
    cost = np.sum(-np.log(yhat[labels==1])) / data.shape[0]

    d3 = (yhat - labels) / data.shape[0]
    gradW2 = np.dot(h.T, d3)
    gradb2 = np.sum(d3,0,keepdims=True)

    dh = np.dot(d3,W2.T)
    grad_h = sigmoid_grad(h) * dh

    gradW1 = np.dot(data.T,grad_h)
    gradb1 = np.sum(grad_h,0)
    ### END YOUR CODE

    ### Stack gradients (do not modify)
    grad = np.concatenate((gradW1.flatten(), gradb1.flatten(),
        gradW2.flatten(), gradb2.flatten()))

    return cost, grad


def sanity_check():
    """
    Set up fake data and parameters for the neural network, and test using
    gradcheck.
    """
    print ("Running sanity check...")

    N = 20
    dimensions = [10, 5, 10]
    data = np.random.randn(N, dimensions[0])   # each row will be a datum
    labels = np.zeros((N, dimensions[2]))
    for i in range(N):
        labels[i, random.randint(0,dimensions[2]-1)] = 1

    params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
        dimensions[1] + 1) * dimensions[2])
    
    gradcheck_naive(lambda params:
        forward_backward_prop(data, labels, params, dimensions), params)

def your_sanity_checks():
    """
    Use this space add any additional sanity checks by running:
        python q2_neural.py
    This function will not be called by the autograder, nor will
    your additional tests be graded.
    """
    print ("Running your sanity checks...")
    ### YOUR CODE HERE
    # raise NotImplementedError
    ### END YOUR CODE


if __name__ == "__main__":
    sanity_check()
#    your_sanity_checks()

Running sanity check...
Gradient check failed.
First gradient error found at index (0,)
Your gradient: 0.000251 	 Numerical gradient: 0.000000


<class 'list'>
